var searchData=
[
  ['observation',['observation',['../classmeta_1_1sequence_1_1observation.html',1,'meta::sequence']]],
  ['okapi_5fbm25',['okapi_bm25',['../classmeta_1_1index_1_1okapi__bm25.html',1,'meta::index']]],
  ['one_5fvs_5fall',['one_vs_all',['../classmeta_1_1classify_1_1one__vs__all.html',1,'meta::classify']]],
  ['one_5fvs_5fone',['one_vs_one',['../classmeta_1_1classify_1_1one__vs__one.html',1,'meta::classify']]],
  ['optional',['optional',['../classmeta_1_1util_1_1optional.html',1,'meta::util']]],
  ['optional_3c_20class_5flabel_20_3e',['optional&lt; class_label &gt;',['../classmeta_1_1util_1_1optional.html',1,'meta::util']]],
  ['optional_3c_20dense_5fmatrix_3c_20double_20_3e_20_3e',['optional&lt; dense_matrix&lt; double &gt; &gt;',['../classmeta_1_1util_1_1optional.html',1,'meta::util']]],
  ['optional_3c_20io_3a_3ammap_5ffile_20_3e',['optional&lt; io::mmap_file &gt;',['../classmeta_1_1util_1_1optional.html',1,'meta::util']]],
  ['optional_3c_20label_5fid_20_3e',['optional&lt; label_id &gt;',['../classmeta_1_1util_1_1optional.html',1,'meta::util']]],
  ['optional_3c_20meta_3a_3aindex_3a_3astring_5flist_20_3e',['optional&lt; meta::index::string_list &gt;',['../classmeta_1_1util_1_1optional.html',1,'meta::util']]],
  ['optional_3c_20meta_3a_3aindex_3a_3avocabulary_5fmap_20_3e',['optional&lt; meta::index::vocabulary_map &gt;',['../classmeta_1_1util_1_1optional.html',1,'meta::util']]],
  ['optional_3c_20meta_3a_3asequence_3a_3aforward_5ftrellis_20_3e',['optional&lt; meta::sequence::forward_trellis &gt;',['../classmeta_1_1util_1_1optional.html',1,'meta::util']]],
  ['optional_3c_20meta_3a_3asequence_3a_3atrellis_20_3e',['optional&lt; meta::sequence::trellis &gt;',['../classmeta_1_1util_1_1optional.html',1,'meta::util']]],
  ['optional_3c_20std_3a_3astring_20_3e',['optional&lt; std::string &gt;',['../classmeta_1_1util_1_1optional.html',1,'meta::util']]],
  ['optional_3c_20tag_5ft_20_3e',['optional&lt; tag_t &gt;',['../classmeta_1_1util_1_1optional.html',1,'meta::util']]],
  ['optional_3c_20uint64_5ft_20_3e',['optional&lt; uint64_t &gt;',['../classmeta_1_1util_1_1optional.html',1,'meta::util']]],
  ['optional_3c_20util_3a_3adisk_5fvector_3c_20crf_5ffeature_5fid_20_3e_20_3e',['optional&lt; util::disk_vector&lt; crf_feature_id &gt; &gt;',['../classmeta_1_1util_1_1optional.html',1,'meta::util']]],
  ['optional_3c_20util_3a_3adisk_5fvector_3c_20double_20_3e_20_3e',['optional&lt; util::disk_vector&lt; double &gt; &gt;',['../classmeta_1_1util_1_1optional.html',1,'meta::util']]],
  ['optional_3c_20util_3a_3adisk_5fvector_3c_20label_5fid_20_3e_20_3e',['optional&lt; util::disk_vector&lt; label_id &gt; &gt;',['../classmeta_1_1util_1_1optional.html',1,'meta::util']]],
  ['optional_3c_20util_3a_3adisk_5fvector_3c_20uint64_5ft_20_3e_20_3e',['optional&lt; util::disk_vector&lt; uint64_t &gt; &gt;',['../classmeta_1_1util_1_1optional.html',1,'meta::util']]],
  ['optional_3c_20value_20_3e',['optional&lt; Value &gt;',['../classmeta_1_1util_1_1optional.html',1,'meta::util']]],
  ['optional_5fdummy_5ft',['optional_dummy_t',['../structmeta_1_1util_1_1optional__dummy__t.html',1,'meta::util']]],
  ['optional_5fstorage',['optional_storage',['../unionmeta_1_1util_1_1optional__storage.html',1,'meta::util']]],
  ['optional_5fstorage_3c_20class_5flabel_20_3e',['optional_storage&lt; class_label &gt;',['../unionmeta_1_1util_1_1optional__storage.html',1,'meta::util']]],
  ['optional_5fstorage_3c_20dense_5fmatrix_3c_20double_20_3e_20_3e',['optional_storage&lt; dense_matrix&lt; double &gt; &gt;',['../unionmeta_1_1util_1_1optional__storage.html',1,'meta::util']]],
  ['optional_5fstorage_3c_20io_3a_3ammap_5ffile_20_3e',['optional_storage&lt; io::mmap_file &gt;',['../unionmeta_1_1util_1_1optional__storage.html',1,'meta::util']]],
  ['optional_5fstorage_3c_20label_5fid_20_3e',['optional_storage&lt; label_id &gt;',['../unionmeta_1_1util_1_1optional__storage.html',1,'meta::util']]],
  ['optional_5fstorage_3c_20meta_3a_3aindex_3a_3astring_5flist_20_3e',['optional_storage&lt; meta::index::string_list &gt;',['../unionmeta_1_1util_1_1optional__storage.html',1,'meta::util']]],
  ['optional_5fstorage_3c_20meta_3a_3aindex_3a_3avocabulary_5fmap_20_3e',['optional_storage&lt; meta::index::vocabulary_map &gt;',['../unionmeta_1_1util_1_1optional__storage.html',1,'meta::util']]],
  ['optional_5fstorage_3c_20meta_3a_3asequence_3a_3aforward_5ftrellis_20_3e',['optional_storage&lt; meta::sequence::forward_trellis &gt;',['../unionmeta_1_1util_1_1optional__storage.html',1,'meta::util']]],
  ['optional_5fstorage_3c_20meta_3a_3asequence_3a_3atrellis_20_3e',['optional_storage&lt; meta::sequence::trellis &gt;',['../unionmeta_1_1util_1_1optional__storage.html',1,'meta::util']]],
  ['optional_5fstorage_3c_20std_3a_3astring_20_3e',['optional_storage&lt; std::string &gt;',['../unionmeta_1_1util_1_1optional__storage.html',1,'meta::util']]],
  ['optional_5fstorage_3c_20tag_5ft_20_3e',['optional_storage&lt; tag_t &gt;',['../unionmeta_1_1util_1_1optional__storage.html',1,'meta::util']]],
  ['optional_5fstorage_3c_20uint64_5ft_20_3e',['optional_storage&lt; uint64_t &gt;',['../unionmeta_1_1util_1_1optional__storage.html',1,'meta::util']]],
  ['optional_5fstorage_3c_20util_3a_3adisk_5fvector_3c_20crf_5ffeature_5fid_20_3e_20_3e',['optional_storage&lt; util::disk_vector&lt; crf_feature_id &gt; &gt;',['../unionmeta_1_1util_1_1optional__storage.html',1,'meta::util']]],
  ['optional_5fstorage_3c_20util_3a_3adisk_5fvector_3c_20double_20_3e_20_3e',['optional_storage&lt; util::disk_vector&lt; double &gt; &gt;',['../unionmeta_1_1util_1_1optional__storage.html',1,'meta::util']]],
  ['optional_5fstorage_3c_20util_3a_3adisk_5fvector_3c_20label_5fid_20_3e_20_3e',['optional_storage&lt; util::disk_vector&lt; label_id &gt; &gt;',['../unionmeta_1_1util_1_1optional__storage.html',1,'meta::util']]],
  ['optional_5fstorage_3c_20util_3a_3adisk_5fvector_3c_20uint64_5ft_20_3e_20_3e',['optional_storage&lt; util::disk_vector&lt; uint64_t &gt; &gt;',['../unionmeta_1_1util_1_1optional__storage.html',1,'meta::util']]],
  ['optional_5fstorage_3c_20value_20_3e',['optional_storage&lt; Value &gt;',['../unionmeta_1_1util_1_1optional__storage.html',1,'meta::util']]]
];
