var searchData=
[
  ['score_5fdata',['score_data',['../structmeta_1_1index_1_1score__data.html',1,'meta::index']]],
  ['scorer',['scorer',['../classmeta_1_1sequence_1_1crf_1_1scorer.html',1,'meta::sequence::crf']]],
  ['segment',['segment',['../classmeta_1_1utf_1_1segmenter_1_1segment.html',1,'meta::utf::segmenter']]],
  ['segmenter',['segmenter',['../classmeta_1_1utf_1_1segmenter.html',1,'meta::utf']]],
  ['semi_5fskeleton_5fanalyzer',['semi_skeleton_analyzer',['../classmeta_1_1analyzers_1_1semi__skeleton__analyzer.html',1,'meta::analyzers']]],
  ['sentence_5fboundary',['sentence_boundary',['../classmeta_1_1analyzers_1_1filters_1_1sentence__boundary.html',1,'meta::analyzers::filters']]],
  ['sequence',['sequence',['../classmeta_1_1sequence_1_1sequence.html',1,'meta::sequence']]],
  ['sequence_5fanalyzer',['sequence_analyzer',['../classmeta_1_1sequence_1_1sequence__analyzer.html',1,'meta::sequence']]],
  ['sgd',['sgd',['../classmeta_1_1classify_1_1sgd.html',1,'meta::classify']]],
  ['sigmoid',['sigmoid',['../classmeta_1_1classify_1_1kernel_1_1sigmoid.html',1,'meta::classify::kernel']]],
  ['sink',['sink',['../classmeta_1_1logging_1_1logger_1_1sink.html',1,'meta::logging::logger']]],
  ['skeleton_5fanalyzer',['skeleton_analyzer',['../classmeta_1_1analyzers_1_1skeleton__analyzer.html',1,'meta::analyzers']]],
  ['smooth_5fhinge',['smooth_hinge',['../structmeta_1_1classify_1_1loss_1_1smooth__hinge.html',1,'meta::classify::loss']]],
  ['sparse_5fvector',['sparse_vector',['../classmeta_1_1util_1_1sparse__vector.html',1,'meta::util']]],
  ['sparse_5fvector_3c_20class_5flabel_2c_20double_20_3e',['sparse_vector&lt; class_label, double &gt;',['../classmeta_1_1util_1_1sparse__vector.html',1,'meta::util']]],
  ['sparse_5fvector_3c_20class_5flabel_2c_20stats_3a_3amultinomial_3c_20term_5fid_20_3e_20_3e',['sparse_vector&lt; class_label, stats::multinomial&lt; term_id &gt; &gt;',['../classmeta_1_1util_1_1sparse__vector.html',1,'meta::util']]],
  ['sparse_5fvector_3c_20t_2c_20double_20_3e',['sparse_vector&lt; T, double &gt;',['../classmeta_1_1util_1_1sparse__vector.html',1,'meta::util']]],
  ['sparse_5fvector_3c_20term_5fid_2c_20double_20_3e',['sparse_vector&lt; term_id, double &gt;',['../classmeta_1_1util_1_1sparse__vector.html',1,'meta::util']]],
  ['sparse_5fvector_3c_20topic_5fid_2c_20double_20_3e',['sparse_vector&lt; topic_id, double &gt;',['../classmeta_1_1util_1_1sparse__vector.html',1,'meta::util']]],
  ['splay_5fcache',['splay_cache',['../classmeta_1_1caching_1_1splay__cache.html',1,'meta::caching']]],
  ['splay_5fcache_5fexception',['splay_cache_exception',['../classmeta_1_1caching_1_1splay__cache_1_1splay__cache__exception.html',1,'meta::caching::splay_cache']]],
  ['squared_5fhinge',['squared_hinge',['../structmeta_1_1classify_1_1loss_1_1squared__hinge.html',1,'meta::classify::loss']]],
  ['string_5flist',['string_list',['../classmeta_1_1index_1_1string__list.html',1,'meta::index']]],
  ['string_5flist_5fwriter',['string_list_writer',['../classmeta_1_1index_1_1string__list__writer.html',1,'meta::index']]],
  ['subtree_5fanalyzer',['subtree_analyzer',['../classmeta_1_1analyzers_1_1subtree__analyzer.html',1,'meta::analyzers']]],
  ['svm_5fwrapper',['svm_wrapper',['../classmeta_1_1classify_1_1svm__wrapper.html',1,'meta::classify']]]
];
