var searchData=
[
  ['dblru_5fcache',['dblru_cache',['../classmeta_1_1caching_1_1dblru__cache.html',1,'meta::caching']]],
  ['debinarizer',['debinarizer',['../classmeta_1_1parser_1_1debinarizer.html',1,'meta::parser']]],
  ['default_5fcollector',['default_collector',['../classmeta_1_1sequence_1_1sequence__analyzer_1_1default__collector.html',1,'meta::sequence::sequence_analyzer']]],
  ['default_5fedge',['default_edge',['../structmeta_1_1graph_1_1default__edge.html',1,'meta::graph']]],
  ['default_5fnode',['default_node',['../structmeta_1_1graph_1_1default__node.html',1,'meta::graph']]],
  ['dense_5fmatrix',['dense_matrix',['../classmeta_1_1util_1_1dense__matrix.html',1,'meta::util']]],
  ['dense_5fmatrix_3c_20double_20_3e',['dense_matrix&lt; double &gt;',['../classmeta_1_1util_1_1dense__matrix.html',1,'meta::util']]],
  ['dense_5fmatrix_3c_20label_5fid_20_3e',['dense_matrix&lt; label_id &gt;',['../classmeta_1_1util_1_1dense__matrix.html',1,'meta::util']]],
  ['depth_5ffeaturizer',['depth_featurizer',['../classmeta_1_1analyzers_1_1depth__featurizer.html',1,'meta::analyzers']]],
  ['directed_5fgraph',['directed_graph',['../classmeta_1_1graph_1_1directed__graph.html',1,'meta::graph']]],
  ['directed_5fgraph',['directed_graph',['../classdirected__graph.html',1,'']]],
  ['directed_5fgraph',['directed_graph',['../classmeta_1_1graph_1_1undirected__graph_1_1directed__graph.html',1,'meta::graph::undirected_graph']]],
  ['directed_5fgraph_5fexception',['directed_graph_exception',['../classmeta_1_1graph_1_1directed__graph__exception.html',1,'meta::graph']]],
  ['dirichlet',['dirichlet',['../classmeta_1_1stats_1_1dirichlet.html',1,'meta::stats']]],
  ['dirichlet_3c_20class_5flabel_20_3e',['dirichlet&lt; class_label &gt;',['../classmeta_1_1stats_1_1dirichlet.html',1,'meta::stats']]],
  ['dirichlet_3c_20term_5fid_20_3e',['dirichlet&lt; term_id &gt;',['../classmeta_1_1stats_1_1dirichlet.html',1,'meta::stats']]],
  ['dirichlet_3c_20topic_5fid_20_3e',['dirichlet&lt; topic_id &gt;',['../classmeta_1_1stats_1_1dirichlet.html',1,'meta::stats']]],
  ['dirichlet_5fprior',['dirichlet_prior',['../classmeta_1_1index_1_1dirichlet__prior.html',1,'meta::index']]],
  ['disk_5findex',['disk_index',['../classmeta_1_1index_1_1disk__index.html',1,'meta::index']]],
  ['disk_5findex_5fimpl',['disk_index_impl',['../classmeta_1_1index_1_1disk__index_1_1disk__index__impl.html',1,'meta::index::disk_index']]],
  ['disk_5fvector',['disk_vector',['../classmeta_1_1util_1_1disk__vector.html',1,'meta::util']]],
  ['disk_5fvector_3c_20crf_5ffeature_5fid_20_3e',['disk_vector&lt; crf_feature_id &gt;',['../classmeta_1_1util_1_1disk__vector.html',1,'meta::util']]],
  ['disk_5fvector_3c_20double_20_3e',['disk_vector&lt; double &gt;',['../classmeta_1_1util_1_1disk__vector.html',1,'meta::util']]],
  ['disk_5fvector_3c_20label_5fid_20_3e',['disk_vector&lt; label_id &gt;',['../classmeta_1_1util_1_1disk__vector.html',1,'meta::util']]],
  ['disk_5fvector_3c_20uint64_5ft_20_3e',['disk_vector&lt; uint64_t &gt;',['../classmeta_1_1util_1_1disk__vector.html',1,'meta::util']]],
  ['disk_5fvector_5fexception',['disk_vector_exception',['../classmeta_1_1util_1_1disk__vector_1_1disk__vector__exception.html',1,'meta::util::disk_vector']]],
  ['document',['document',['../classmeta_1_1corpus_1_1document.html',1,'meta::corpus']]],
  ['dual_5fperceptron',['dual_perceptron',['../classmeta_1_1classify_1_1dual__perceptron.html',1,'meta::classify']]]
];
