var searchData=
[
  ['tag_5ffeaturizer',['tag_featurizer',['../classmeta_1_1analyzers_1_1tag__featurizer.html',1,'meta::analyzers']]],
  ['tagger',['tagger',['../classmeta_1_1sequence_1_1crf_1_1tagger.html',1,'meta::sequence::crf']]],
  ['task',['task',['../structmeta_1_1parallel_1_1thread__pool_1_1task.html',1,'meta::parallel::thread_pool']]],
  ['thread_5fpool',['thread_pool',['../classmeta_1_1parallel_1_1thread__pool.html',1,'meta::parallel']]],
  ['token_5fstream',['token_stream',['../classmeta_1_1analyzers_1_1token__stream.html',1,'meta::analyzers']]],
  ['token_5fstream_5fexception',['token_stream_exception',['../classmeta_1_1analyzers_1_1token__stream_1_1token__stream__exception.html',1,'meta::analyzers::token_stream']]],
  ['training_5fbatch',['training_batch',['../structmeta_1_1parser_1_1sr__parser_1_1training__batch.html',1,'meta::parser::sr_parser']]],
  ['training_5fdata',['training_data',['../classmeta_1_1parser_1_1sr__parser_1_1training__data.html',1,'meta::parser::sr_parser']]],
  ['training_5foptions',['training_options',['../structmeta_1_1sequence_1_1perceptron_1_1training__options.html',1,'meta::sequence::perceptron']]],
  ['training_5foptions',['training_options',['../structmeta_1_1parser_1_1sr__parser_1_1training__options.html',1,'meta::parser::sr_parser']]],
  ['transformer',['transformer',['../classmeta_1_1utf_1_1transformer.html',1,'meta::utf']]],
  ['transition',['transition',['../classmeta_1_1parser_1_1transition.html',1,'meta::parser']]],
  ['transition_5ffinder',['transition_finder',['../classmeta_1_1parser_1_1transition__finder.html',1,'meta::parser']]],
  ['transition_5fmap',['transition_map',['../classmeta_1_1parser_1_1transition__map.html',1,'meta::parser']]],
  ['tree_5fanalyzer',['tree_analyzer',['../classmeta_1_1analyzers_1_1tree__analyzer.html',1,'meta::analyzers']]],
  ['tree_5ffeaturizer',['tree_featurizer',['../classmeta_1_1analyzers_1_1tree__featurizer.html',1,'meta::analyzers']]],
  ['tree_5ftransformer',['tree_transformer',['../classmeta_1_1parser_1_1tree__transformer.html',1,'meta::parser']]],
  ['trellis',['trellis',['../classmeta_1_1sequence_1_1trellis.html',1,'meta::sequence']]],
  ['trivial_5finit_5ft',['trivial_init_t',['../structmeta_1_1util_1_1trivial__init__t.html',1,'meta::util']]]
];
