#include "index/ranker/ranker.h"
#include "index/ranker/absolute_discount.h"
#include "index/ranker/dirichlet_prior.h"
#include "index/ranker/jelinek_mercer.h"
#include "index/ranker/lm_ranker.h"
#include "index/ranker/okapi_bm25.h"
#include "index/ranker/pivoted_length.h"
