#include "classify/classifier/naive_bayes.h"
#include "classify/classifier/liblinear_svm.h"
#include "classify/classifier/perceptron.h"
#include "classify/classifier/linear_svm.h"
#include "classify/classifier/liblinear_svm.h"
